include:
  - local: .common.gitlab-ci.yml
  - local: .ansible.gitlab-ci.yml
  - local: .post.gitlab-ci.yml

stages:
  - pre
  - test
  - build
  - migration
  - deploy
  - post

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
      when: always
      variables:
        PIPELINE_TYPE: "version-tag"
    - if: '$CI_COMMIT_MESSAGE =~ /\[skip gitlab-ci\]/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH'
      when: always
    - when: never

variables:
  GRADLE_JVM_OPTS: "-Xmx4096m"
  GRADLE_OPTS: "-Dorg.gradle.workers.max=4"
  SERVICE_NAME: "dptb"
  YOUTRACK_PROJECT: "DPTB"

default:
  interruptible: true

generate-version:
  extends:
    - .default-tags
    - .branch-only
  stage: pre
  image:
    name: gittools/gitversion:6.5.0
    entrypoint: [""]
  variables:
    GIT_DEPTH: 0
  before_script:
    - git fetch --tags
  script:
    - /tools/dotnet-gitversion /showconfig
    - /tools/dotnet-gitversion /diag /verbosity Diagnostic
    - /tools/dotnet-gitversion /output buildserver
  artifacts:
    expire_in: 1 day
    reports:
      dotenv: gitversion.properties
    paths:
      - gitversion.properties

test:
  extends:
    - .default-tags
    - .branch-only
  stage: test
  image: gradle:8.4-jdk17
  variables:
    GRADLE_USER_HOME: ".gradle"
    TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TEST_TOKEN}
  cache:
    - key: gradle-cache-${CI_PROJECT_ID}
      paths:
        - .gradle
    - key: gradle-build-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}
      paths:
        - build/
  before_script:
    - |
      curl -fsSL https://cli.codecov.io/latest/linux/codecov -o codecov
      chmod +x codecov
  script:
    - gradle test

    - test -f build/jacoco/coverage.xml

    - |
      ./codecov create-commit
      ./codecov create-report
      ./codecov do-upload -Z -n "codecov-${CI_PROJECT_ID}-${CI_COMMIT_REF_NAME}"
  artifacts:
    expire_in: 1 day
    when: always
    paths:
      - build/jacoco/coverage.xml
      - build/test-results/test
    reports:
      junit: "build/test-results/test/*.xml"
      coverage_report:
        coverage_format: jacoco
        path: "build/jacoco/coverage.xml"

build-jar:
  extends:
    - .default-tags
    - .branch-only
  stage: build
  image: gradle:8.4-jdk17
  needs:
    - test
  variables:
    GRADLE_USER_HOME: ".gradle"
  cache:
    - key: gradle-cache-${CI_PROJECT_ID}
      paths:
        - .gradle
  script:
    - gradle assemble
  artifacts:
    expire_in: 1 day
    paths:
      - build/libs/drinking-ponies.jar

build-image:
  extends:
    - .default-tags
    - .branch-only
  stage: build
  image: docker:27
  needs:
    - job: generate-version
      artifacts: true
    - job: build-jar
      artifacts: true
  before_script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  script:
    - echo "image tag=${GitVersion_SemVer}"
    - |
      docker build -t "${CI_REGISTRY_IMAGE}:${GitVersion_SemVer}" .
      docker push "${CI_REGISTRY_IMAGE}:${GitVersion_SemVer}"
      if [ "${CI_COMMIT_BRANCH}" = "master" ]; then
        docker tag "${CI_REGISTRY_IMAGE}:${GitVersion_SemVer}" "${CI_REGISTRY_IMAGE}:latest"
        docker push "${CI_REGISTRY_IMAGE}:latest"
      fi
  after_script:
    - |
      docker rmi "${CI_REGISTRY_IMAGE}:${GitVersion_SemVer}" || true
      docker rmi "${CI_REGISTRY_IMAGE}:latest" || true
